### ISSUE TITLE
How does one trigger an alarm zone via MQTT

### ISSUE THREAD

**Issue by Fezile01** [jimtng/dscalarm-mqtt#1]
How does one trigger an alarm zone via MQTT. As my alarm is currently monitored by a security company, would it be possible to trigger a specific zone via MQTT from Home Assistant to despatch a security vehicle?

**Comment by jimtng** [comment]
If your panel has been programmed to do so, you can send either of these commands according to your requirement:
- "keypad auxiliary alarm" - send "a"
- "keypad panic alarm" - send "p" 

You can send those commands using keypad/set mqtt topic

**Comment by concifederico** [comment]
Hi,
I'm not an expert but I'm almost sure that the MQTT topic:
keypad/set 
in not available at least in this distro..
Any help?
Regards,

Federico
