### ISSUE TITLE
MQTT Topic keypad/set is not available

### ISSUE THREAD

**Issue by jimtng** [jimtng/dscalarm-mqtt#5]
Hi,
I'm not an expert but I'm almost sure that the MQTT topic:
keypad/set 
in not available at least in this distro..
Any help?
Regards,

Federico

_Originally posted by @concifederico in https://github.com/jimtng/dscalarm-mqtt/issues/1#issuecomment-1687182248_

**Comment by jimtng** [comment]
@concifederico Which version are you using? The older version used the Homie convention, and the new version now uses ESPHome framework. In the ESPHome framework, you'd send the message using `devicename/write`. See https://github.com/jimtng/dscalarm-mqtt/blob/404860dce17827cfd9fee4ab8f84bc6fc8ef61d3/dsc-alarm.yaml#L109-L111

**Comment by concifederico** [comment]
Hi, you are completely right. I'm a bit confused. Lets say I want to send an *2 command to check error messages in the panel.
Should I publish the payload *2 to the topic /dsc-alarn/command/write? That payload should be sent as raw?
Regards,

Federico

**Comment by jimtng** [comment]
Yes, just publish `*2` (a string). BTW Topics usually don't start with a `/`. So the topic is just `dsc-alarn/command/write`

**Comment by concifederico** [comment]
Hi, It's working perfectly! I had a foolish bad soldering joint in the D8 - 1K Resistor. :(
Thank you very much!!
Regards,

Federico

**Comment by jimtng** [comment]
Awesome!
